package minitwitter.GUI;

import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeCellRenderer;
import minitwitter.Observer.TreeObserver;
import minitwitter.TwitterMessage;
import minitwitter.User;
import minitwitter.UserGroup;
import minitwitter.Visitor.SizeVisitor;


/**
 * This class represent AdminControlPanel GUI. On this GUI, it can add
 * new users or new user groups, view informations, or open a user view.
 * @author Seungyun Lee
 */
public class AdminControlPanel extends javax.swing.JFrame {

    // Only creating one instance
    private static AdminControlPanel instance;
    private UserGroup rootGroup;
    private SizeVisitor sizeVisitor;
    private TreeObserver treeObserver;
    private DefaultTreeModel treeModel;
    private DefaultMutableTreeNode rootNode;
    private User userReference;
    private TwitterMessage twitterMessageReference;
  
    /**
     * This is the constructor to create only one instance of AdminControlPanel.
     */
    private AdminControlPanel() {
        initComponents();
        rootGroup = new UserGroup("Root");
        // User reference to visit user's size
        userReference = new User("userReference");
        // Twitter message reference to visit its size.
        twitterMessageReference = new TwitterMessage("twitterMessageReference", 
                "This is a reference.");
        rootNode = new DefaultMutableTreeNode(rootGroup.getId());
        initalizeTree();
        treeObserver = new TreeObserver(tree, treeModel);
        sizeVisitor = new SizeVisitor();
        rootGroup.accept(sizeVisitor);
        rootGroup.attach(treeObserver);        
    }

    /**
     * This method returns the instance of AdminControlPanel.
     * @return instance of AdminControlPanel
     */
    public static AdminControlPanel getInstance() {
        if(instance == null){
            synchronized (AdminControlPanel.class) {
                if(instance == null){
                    instance = new AdminControlPanel();
                }
            }
        }
        return instance;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        treePane = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();
        addUserButton = new javax.swing.JButton();
        addGroupButton = new javax.swing.JButton();
        openUserViewButton = new javax.swing.JButton();
        showUserTotalButton = new javax.swing.JButton();
        showGroupTotalButton = new javax.swing.JButton();
        showMessagesTotalButton = new javax.swing.JButton();
        showPositivePercentageButton = new javax.swing.JButton();
        userIDTextField = new javax.swing.JTextField();
        groupIDTextField = new javax.swing.JTextField();
        warningLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        tree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        treePane.setViewportView(tree);

        addUserButton.setText("Add User");
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        addGroupButton.setText("Add Group");
        addGroupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGroupButtonActionPerformed(evt);
            }
        });

        openUserViewButton.setText("Open User View");
        openUserViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openUserViewButtonActionPerformed(evt);
            }
        });

        showUserTotalButton.setText("Show User Total");
        showUserTotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showUserTotalButtonActionPerformed(evt);
            }
        });

        showGroupTotalButton.setText("Show Group Total");
        showGroupTotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showGroupTotalButtonActionPerformed(evt);
            }
        });

        showMessagesTotalButton.setText("Show Messages Total");
        showMessagesTotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMessagesTotalButtonActionPerformed(evt);
            }
        });

        showPositivePercentageButton.setText("Show Positive %");
        showPositivePercentageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPositivePercentageButtonActionPerformed(evt);
            }
        });

        userIDTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userIDTextField.setToolTipText("");

        groupIDTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        warningLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(treePane, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(warningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showMessagesTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showPositivePercentageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showUserTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showGroupTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(groupIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(openUserViewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(userIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(warningLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(groupIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addGroupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openUserViewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(showUserTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showGroupTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(showMessagesTotalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showPositivePercentageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(treePane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method lets the user to open a user view that the user selected to 
     * view.
     */
    private void openUserViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openUserViewButtonActionPerformed
        warningLabel.setText("");
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) 
                tree.getLastSelectedPathComponent();
        // Checks if nothing is selected
        if (selectedNode != null) {
            String ID = selectedNode.toString();
            rootGroup.findUserGroup(ID);
            UserGroup.getUserGroup();
            boolean isUser = !UserGroup.isFoundUserGroup();
            // Checks if a user is selected
            if (isUser) {
                new UserView(ID, rootGroup);
            } else {
                warningLabel.setText("Select a User");
            }
        } else {
            warningLabel.setText("Select a User");
        }
    }//GEN-LAST:event_openUserViewButtonActionPerformed

    /**
     * This method shows an information dialog with the user size.
     */
    private void showUserTotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showUserTotalButtonActionPerformed
        sizeVisitor.visitUser(userReference);
        createDialog("User Total", "User Total: ", sizeVisitor.getUserSize());
    }//GEN-LAST:event_showUserTotalButtonActionPerformed

    /**
     * This method shows an information dialog with the user group size.
     */
    private void showGroupTotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showGroupTotalButtonActionPerformed
        sizeVisitor.visitGroup(rootGroup);
        createDialog("Group Total", "Group Total: ", sizeVisitor.getUserGroupSize());
    }//GEN-LAST:event_showGroupTotalButtonActionPerformed

    /**
     * This method shows an information dialog with the message size.
     */
    private void showMessagesTotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMessagesTotalButtonActionPerformed
        sizeVisitor.visitTwitterMessage(twitterMessageReference);
        createDialog("Message Total", "Message Total: ", sizeVisitor.getMessageSize());
    }//GEN-LAST:event_showMessagesTotalButtonActionPerformed

    /**
     * This method shows an information dialog with the positive message percentage.
     */
    private void showPositivePercentageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPositivePercentageButtonActionPerformed
        sizeVisitor.visitTwitterMessage(twitterMessageReference);
        double positivePercent = 0;
        if (sizeVisitor.getMessageSize() > 0) {
           positivePercent = ((sizeVisitor.getPositiveMessageSize() * 1.0) / 
                sizeVisitor.getMessageSize()) * 100;
        }
        createDialog("Positive %", "Positive %: ", positivePercent);
    }//GEN-LAST:event_showPositivePercentageButtonActionPerformed

    /**
     * This method adds a new user.
     */
    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        addElement(userIDTextField, true);       
    }//GEN-LAST:event_addUserButtonActionPerformed

    /**
     * This method adds a new user group.
     */
    private void addGroupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGroupButtonActionPerformed
        addElement(groupIDTextField, false);
    }//GEN-LAST:event_addGroupButtonActionPerformed
    
    /**
     * This method adds either a new user or a new user group. It does
     * error checking.
     * @param textField, either userIDTextField or userGroupIDTextField  
     * @param isAddUser, true, if add user button is clicked; false, if add user
     *                  group is clicked
     */
    private void addElement(JTextField textField, boolean isAddUser) {
        warningLabel.setText("");
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) 
                tree.getLastSelectedPathComponent();
        // Nothing is selected
        if (selectedNode != null) {
            String selectedID = selectedNode.toString();
            rootGroup.findUserGroup(selectedID);
            UserGroup selectedGroup = UserGroup.getUserGroup();
            // Checks if selected one is a user group
            if (UserGroup.isFoundUserGroup()) {
                if (!textField.getText().trim().equals("")) {
                    String newID = textField.getText();
                    // Check if there is a user/user group with the same ID
                    if (!rootGroup.search(newID)) {
                        // Add user
                        if (isAddUser) {
                            User user = new User(newID);
                            User.increaseUserSize();
                            DefaultMutableTreeNode newNode = 
                                    new DefaultMutableTreeNode(user.getId());
                            rootGroup.add(user, selectedNode, newNode);
                            textField.setText("");
                        // Add user group
                        } else {
                            UserGroup userGroup = new UserGroup(newID);
                            DefaultMutableTreeNode newNode = 
                                new DefaultMutableTreeNode(userGroup.getId());
                            rootGroup.add(userGroup, selectedNode, newNode);
                            textField.setText("");
                        }
                    } else {
                        warningLabel.setText("The ID already exists");
                    }                   
                } else {
                    warningLabel.setText("Enter ID");
                }
            } else {
                warningLabel.setText("Select a Group");
            }
        } else {
            warningLabel.setText("Select a Group");
        }
    }
    
    /**
     * This method creates an information dialog with given information.
     * @param title, title of the information
     * @param message, message of the information
     * @param number, size
     */
    private void createDialog(String title, String message, double number) {
        message = message + number;
        new InformationDialog(title, message);
    }
    
    /**
     * This method initializes the tree and shows it with the root group first.
     */
    private void initalizeTree() {    
        tree = new JTree(rootNode);
        tree.setCellRenderer(new CustomTreeCellRenderer(rootGroup));
        treeModel = (DefaultTreeModel) tree.getModel();
        treePane.setViewportView(tree);
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGroupButton;
    private javax.swing.JButton addUserButton;
    private javax.swing.JTextField groupIDTextField;
    private javax.swing.JButton openUserViewButton;
    private javax.swing.JButton showGroupTotalButton;
    private javax.swing.JButton showMessagesTotalButton;
    private javax.swing.JButton showPositivePercentageButton;
    private javax.swing.JButton showUserTotalButton;
    private javax.swing.JTree tree;
    private javax.swing.JScrollPane treePane;
    private javax.swing.JTextField userIDTextField;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
}

/**
 * This class is to customize the tree view in order to distinguish between
 * users and user groups.
 */
class CustomTreeCellRenderer implements TreeCellRenderer {
    
    private JLabel label;
    private UserGroup root;
    
    /**
     * This sets the label and root with the given ones.
     * @param root, root group
     */
    CustomTreeCellRenderer(UserGroup root) {
        this.root = root;
        label = new JLabel();  
    }

    @Override
    public Component getTreeCellRendererComponent(JTree tree, Object value, 
            boolean selected, boolean expanded, boolean leaf, int row, 
            boolean hasFocus) {
        root.findUserGroup(((DefaultMutableTreeNode) value).toString());
        // Checks if it is a user group
        if (UserGroup.isFoundUserGroup()) {
            UserGroup userGroup = UserGroup.getUserGroup();
            label.setText("Group: " + userGroup.getId());
        } else {
            label.setText("User: " + value);
        }
        return label;
    }
    
}
